### ISSUE TITLE
current master broken (git commit ID c75b5bf)

### ISSUE THREAD

**Issue by benkinooby** [OPCFoundation/UA-ModelCompiler#60] opened 2020-09-26 07:38 UTC
Hi,

UA-ModelCompiler fails to build models it was capable of building before.
current git commit ID: c75b5bfe94b8adb448d54cabe7d4ad170adb412b
last working commit ID: 3754f9bb141b33d0f2a32cad984795295a060782 ( tag: UA-1.04.7-2020-07-15)

```
PS C:\UA-ModelCompiler\Bin\Release> .\Opc.Ua.ModelCompiler.exe -d2 C:\opcua-animal-cs\animalModel.xml -cg C:\opcua-animal-cs\animalModel.csv -o C:\opcua-animal-cs\output -console

Error parsing file C:\opcua-animal-cs\animalModel.xml
   at ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in C:\UA-ModelCompiler\ModelCompiler\ModelDesignerValidator.cs:line 1115
   at ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId, String specificationVersion) in C:\UA-ModelCompiler\ModelCompiler\ModelGenerator2.cs:line 99
   at ModelCompiler.Program.ProcessCommandLine2(List`1 tokens) in C:\UA-ModelCompiler\ModelCompiler\Program.cs:line 424
```

I am testing with
https://github.com/Pro/opcua-modeling-tutorial
https://github.com/Pro/opcua-animal-cs

**Comment by benkinooby** [comment] 2020-11-21 10:09
Improved instructions for reproduction with the following ModelDesign file as minimum working example:

```
<?xml version="1.0" encoding="utf-8"?>

<ModelDesign
  xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ua="http://opcfoundation.org/UA/"
  xmlns:FooZbrFlt="https://new.foo.com/zebra-compression/flattening-and-subspacefolding/UA/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  TargetNamespace="https://new.foo.com/zebra-compression/flattening-and-subspacefolding/UA/"
  xmlns="http://opcfoundation.org/UA/ModelDesign.xsd">

  <Namespaces>
    <Namespace Name="FooZbrFlt" Prefix="FooFlt">https://new.foo.com/zebra-compression/flattening-and-subspacefolding/UA/</Namespace>
    <Namespace Name="OpcUa" Version="1.03" PublicationDate="2013-12-02T00:00:00Z">http://opcfoundation.org/UA/</Namespace>
  </Namespaces>
  

    <!-- Instantiate at least one variable (or object, or view, or ...) in namespace.
    Compiling an empty namespace will fail with error message:
      Object reference not set to an instance of an object.
    See https://github.com/OPCFoundation/UA-ModelCompiler/issues/68 -->
  
  <View SymbolicName="FooZbrFlt:MyView">
    <Description>Dummy view</Description>
    <References>
      <Reference IsInverse="true">
        <ReferenceType>ua:Organizes</ReferenceType>
        <TargetId>ua:ObjectsFolder</TargetId>
      </Reference>
    </References>
  </View>
  
</ModelDesign>
```

```
PS C:\UA-ModelCompiler> git checkout 3754f9b
PS C:\UA-ModelCompiler> git submodule init
PS C:\UA-ModelCompiler> & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe' '.\ModelCompiler Solution.sln' /p:Configuration=Release
PS C:\UA-ModelCompiler> cd .\Bin\Release\
PS C:\UA-ModelCompiler\Bin\Release> .\Opc.Ua.ModelCompiler.exe -d2 C:\opcua-modeling-tutorial\FooFltModel.xml -cg C:\opcua-modeling-tutorial\FooFltModel.csv -o C:\opcua-modeling-tutorial\FooFltModel -console -version v104
PS C:\UA-ModelCompiler\Bin\Release> 
```

FooFltModel.xml compiled successfully!

```
PS C:\UA-ModelCompiler> git checkout master
PS C:\UA-ModelCompiler> git rev-parse HEAD
c75b5bfe94b8adb448d54cabe7d4ad170adb412b
PS C:\UA-ModelCompiler> git submodule init
PS C:\UA-ModelCompiler> & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe' '.\ModelCompiler Solution.sln' /p:Configuration=Release
PS C:\UA-ModelCompiler> cd .\Bin\Release\
PS C:\UA-ModelCompiler\Bin\Release> .\Opc.Ua.ModelCompiler.exe -d2 C:\opcua-modeling-tutorial\FooFltModel.xml -cg C:\opcua-modeling-tutorial\FooFltModel.csv -o C:\opcua-modeling-tutorial\FooFltModel -console -version v104
Object reference not set to an instance of an object.
   at ModelCompiler.ModelCompilerValidator.SetStaticNodeIdRanges(ModelDesign dictionary) in C:\UA-ModelCompiler\ModelCompiler\ModelDesignerValidator.cs:line 983
   at ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in C:\UA-ModelCompiler\ModelCompiler\ModelDesignerValidator.cs:line 1235
   at ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId, String specificationVersion) in C:\UA-ModelCompiler\ModelCompiler\ModelGenerator2.cs:line 98
   at ModelCompiler.Program.ProcessCommandLine2(List`1 tokens) in C:\UA-ModelCompiler\ModelCompiler\Program.cs:line 422
PS C:\UA-ModelCompiler\Bin\Release>
```

**Comment by benkinooby** [comment] 2021-02-11 07:24
Hi,

why is this issue closed without comment or fix?
Is there something wrong in my reproduction?

**Comment by opcfoundation-org** [comment] 2021-02-11 08:36
The issue should have fixed properly last year.
I assumed it was a stale post.
Can you confirm the issue is gone?

**Comment by buzzfrog** [comment] 2021-02-23 12:47
I'm not sure if this is related, but I tested today and got this exception:
Object reference not set to an instance of an object.
at ModelCompiler.ModelCompilerValidator.SetStaticNodeIdRanges(ModelDesign dictionary) in C:\git\UA-ModelCompiler\ModelCompiler\ModelDesignerValidator.cs:line 983 at ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in C:\git\UA-ModelCompiler\ModelCompiler\ModelDesignerValidator.cs:line 1235 at ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId, String specificationVersion) in C:\git\UA-ModelCompiler\ModelCompiler\ModelGenerator2.cs:line 98 at ModelCompiler.Program.ProcessCommandLine2(List`1 tokens) in C:\git\UA-ModelCompiler\ModelCompiler\Program.cs:line 422

**Comment by benkinooby** [comment] 2021-02-23 15:10
@buzzfrog Thank you for testing. The lack of formatting in your error message makes it hard to read.

Which git commit ID are you using?
Can you share the model you're using for reproduction?

**Comment by opcfoundation-org** [comment] 2021-02-23 15:33
Fix is in the member only repo:
https://github.com/OPCF-Members/UA-ModelCompiler/commit/e3f30c1aa443365de7abcf2e50feb7c3d01a0cff

Waiting for approval to push to public repo.

**Comment by benkinooby** [comment] 2021-02-23 15:36
Hi,
is there a way for others & me to avoid re-reporting of already known and fixed issues in the public repository?

**Comment by buzzfrog** [comment] 2021-02-23 16:02
It seems to be solved (soon). It was the latest version. @benkinooby your workaround worked for me.

**Comment by opcfoundation-org** [comment] 2021-02-23 16:02
@benkinooby 
This fix came from pull request that was merged into the member-only repo.
https://github.com/OPCFoundation/UA-ModelCompiler/pull/70

**Comment by benkinooby** [comment] 2021-02-23 17:39
@opcfoundation-org Thank you for pointing out #70

Slightly off-topic:
Investigating other PRs such as #62 and #63 I noticed that merging public pull requests manually to the members-only repository first seems to be a common procedure. Then again, other PRs such as #55 were merged directly. What is your policy for accepting pull requests?

**Comment by opcfoundation-org** [comment] 2021-02-23 18:03
@benkinooby 
I could probably accept the pull requests and apply the changes with worrying about merge issues later.
I only applied to the member-only repo this time because I believe the merge was about to happen soon.

**Comment by opcfoundation-org** [comment] 2021-08-24 08:50
Old thread.

**Closed** 2021-08-24 08:49 UTC
